package bolt;

import backtype.storm.task.OutputCollector;
import backtype.storm.task.TopologyContext;
import backtype.storm.topology.OutputFieldsDeclarer;
import backtype.storm.topology.base.BaseRichBolt;
import backtype.storm.tuple.Tuple;
import org.apache.commons.lang.StringUtils;
import org.apache.log4j.Logger;

import java.util.HashMap;
import java.util.Map;
import java.util.StringTokenizer;

/**
 * Created with IntelliJ IDEA.
 * User: qadeer
 * Date: 06.09.13
 * Time: 16:38
 * To change this template use File | Settings | File Templates.
 */
public class SentimentBolt extends BaseRichBolt {
    private OutputCollector _collector;
    private static final Logger LOG = Logger.getLogger(SentimentBolt.class);



    private Map<String, Integer> sentiments = new HashMap<String, Integer>();


    @Override
    public void execute(Tuple tuple) {
        //TODO make use of the language information. If the language is spanish ("es"), we calculate the sentiment value
        String language = "?";
        String text = "?";

        if (StringUtils.equals(language, "no")) {
            double sentimentValue = calculateSentimentValue(text);

            //TODO Emit both the text and its sentimentValue
        }
        // Confirm that this tuple has been treated.
        _collector.ack(tuple);

    }


    /**
     * Calculating the sentiment value for a given text
     * @param text
     * @return
     */
    private double calculateSentimentValue(String text) {
        StringTokenizer st = new StringTokenizer(text);

        int numberOfSentiments = 0;
        int sum = 0;
        while (st.hasMoreElements()) {
            String term = (String) st.nextElement();

            if (sentiments.containsKey(term)) {
                numberOfSentiments++;
                sum += sentiments.get(term);
            }
        }

        double sentimentValue = 0;
        if (numberOfSentiments > 0)
            sentimentValue = sum / numberOfSentiments;
        return sentimentValue;
    }

    @Override
    public void declareOutputFields(OutputFieldsDeclarer outputFieldsDeclarer) {
        //TODO Declare your output fields
    }

    @Override
    public void cleanup() {
        super.cleanup();

    }


    @Override
    public void prepare(Map map, TopologyContext topologyContext, OutputCollector outputCollector) {
        _collector = outputCollector;
        sentiments.put("dejar", -2);
        sentiments.put("dejado", -2);
        sentiments.put("dejo", -2);
        sentiments.put("secuestrado", -1);
        sentiments.put("secuestro", -1);
        sentiments.put("a bordo", 1);
        sentiments.put("grasiento", -2);
        sentiments.put("perezoso", -2);
        sentiments.put("desvergonzado", -2);
        sentiments.put("idiota", -2);
        sentiments.put("nulo", -1);
        sentiments.put(":-)", 2);
        sentiments.put(":)", -5);
        sentiments.put("(-:", 2);
        sentiments.put("(:", 2);
        sentiments.put("B-)", 2);
        sentiments.put(";-)", 2);
        sentiments.put(";)", 2);
        sentiments.put(":-(", -2);
        sentiments.put(":(", -2);
        sentiments.put(")-:", -2);
        sentiments.put("):", -2);
        sentiments.put("abuso", -3);
        sentiments.put("maltrarado", -3);
        sentiments.put("maltrato", -3);
        sentiments.put("aceptado", 1);
        sentiments.put("aceptar", 1);
        sentiments.put("accidente", -2);
        sentiments.put("involuntario", -2);
        sentiments.put("accidente", -2);
        sentiments.put( "accidentes", -2);
        sentiments.put( "lograr", 2);
        sentiments.put( "cumplida", 2);
        sentiments.put( "lograr", 2);
        sentiments.put( "acusación", -2);
        sentiments.put( "acusaciones", -2);
        sentiments.put( "acusación", -2);
        sentiments.put( "acusados", -2);
        sentiments.put( "dolor", -2);
        sentiments.put( "obtenible", 1);
        sentiments.put( "absuelto", 2);
        sentiments.put( "admitir", -1);
        sentiments.put( "admitir", -1);
        sentiments.put( "admitió", -1);
        sentiments.put( "adoptar", 1);
        sentiments.put( "adoptar", 1);
        sentiments.put( "avanzada", 1);
        sentiments.put( "afectada", -1);
        sentiments.put( "miedo", -2);
        sentiments.put( "agresivo", -2);
        sentiments.put( "agresión", -2);
        sentiments.put( "agresiones", -2);
        sentiments.put( "de acuerdo", 1);
        sentiments.put( "de acuerdo", 1);
        sentiments.put( "de acuerdo", 1);
        sentiments.put( "alarma", -2);
        sentiments.put( "alarmante", -2);
        sentiments.put( "alarmistas", -2);
        sentiments.put( "alas", -1);
        sentiments.put( "alerta", -1);
        sentiments.put( "alienación", -2);
        sentiments.put( "en vivo", 1);
        sentiments.put( "alérgica", -2);
        sentiments.put( "permitir", 1);
        sentiments.put( "solo", -2);
        sentiments.put( "asombro", 2);
        sentiments.put( "increíble", 4);
        sentiments.put( "ambicioso", 2);
        sentiments.put( "entretener", 3);
        sentiments.put( "divertida", 3);
        sentiments.put( "deportes acuáticos", 3);
        sentiments.put( "placeres", 3);
        sentiments.put( "ira", -3);
        sentiments.put( "ira", -3);
        sentiments.put( "molestar", -2);
        sentiments.put( "irritante", -2);
        sentiments.put( "molesto", -2);
        sentiments.put( "anti", -1);
        sentiments.put( "ansiedad", -2);
        sentiments.put( "ansiedad", -2);
        sentiments.put( "apocalíptica", -2);
        sentiments.put( "ruidos", -2);
        sentiments.put( "aplaudió", 2);
        sentiments.put( "aplausos", 2);
        sentiments.put( "aplaudir", 2);
        sentiments.put( "aplausos", 2);
        sentiments.put( "agradecimiento", 2);
        sentiments.put( "aprobación", 2);
        sentiments.put( "aprobado", 2);
        sentiments.put( "aprobar", 2);
        sentiments.put( "lo siento", -1);
        sentiments.put( "disculpó", -1);
        sentiments.put( "lo siento", -1);
        sentiments.put( "lamenta", -1);
        sentiments.put( "disculpa", -1);
        sentiments.put( "ardiente", 1);
        sentiments.put( "detención", -2);
        sentiments.put( "detenciones", -2);
        sentiments.put( "disputa", -2);
        sentiments.put( "detenido", -3);
        sentiments.put( "arrogante", -2);
        sentiments.put( "vergüenza", -2);
        sentiments.put( "culo", -4);
        sentiments.put( "culo", -4);
        sentiments.put( "a tope", -2);
        sentiments.put( "intento de asesinato", -3);
        sentiments.put( "asesinatos", -3);
        sentiments.put( "activo", 2);
        sentiments.put( "activos", 2);
        sentiments.put( "capullo", -4);
        sentiments.put( "mierda", -2);
        sentiments.put( "mierda", -2);
        sentiments.put( "statan", -4);
        sentiments.put( "ataque", -1);
        sentiments.put( "ataque", -1);
        sentiments.put( "ataque", -1);
        sentiments.put( "ataque", -1);
        sentiments.put( "daños y perjuicios", -2);
        sentiments.put( "dork", -5);
        sentiments.put( "kipeste", -3);
        sentiments.put( "kip", -3);
        sentiments.put( "aburrido", -2);
        sentiments.put( "Kiper", -2);
        sentiments.put( "desafortunado", -2);
        sentiments.put( "atraer", 1);
        sentiments.put( "atrae", 1);
        sentiments.put( "atraer", 2);
        sentiments.put( "faenmag", -4);
        sentiments.put( "infierno", -3);
        sentiments.put( "gallo", -3);
        sentiments.put( "atracción", 2);
        sentiments.put( "atracciones", 2);
        sentiments.put( "sala", -1);
        sentiments.put( "evitado", -1);
        sentiments.put( "evita", -1);
        sentiments.put( "evitar", -1);
        sentiments.put( "evitado", -1);
        sentiments.put( "evitar", -1);
        sentiments.put( "espera", -1);
        sentiments.put( "anticipada", -1);
        sentiments.put( "espera", -1);
        sentiments.put( "precio", 3);
        sentiments.put( "asignado", 3);
        sentiments.put( "premios", 3);
        sentiments.put( "impresionante", 4);
        sentiments.put( "horrible", -3);
        sentiments.put( "hacha", -1);
        sentiments.put( "despedido", -1);
        sentiments.put( "compatible", 1);
        sentiments.put( "Copia de seguridad", 2);
        sentiments.put( "crestas", 1);
        sentiments.put( "malo", -3);
        sentiments.put( "malo", -3);
        sentiments.put( "rescate", -2);
        sentiments.put( "engañar", -2);
        sentiments.put( "engañado",-2);
        sentiments.put( "embauca", -2);
        sentiments.put( "prohibición", -2);
        sentiments.put( "desaparecer", -1);
        sentiments.put( "quiebra", -3);
        sentiments.put( "bankster", -3);
        sentiments.put( "prohibido", -2);
        sentiments.put( "ganga", 2);
        sentiments.put( "barrera", -2);
        sentiments.put( "capullo", -5);
        sentiments.put( "pendejos", -5);
        sentiments.put( "batalla", -1);
        sentiments.put( "batallas", -1);
        sentiments.put( "hit", -1);
        sentiments.put( "bello", 3);
        sentiments.put( "Amado", 3);
        sentiments.put( "beneficio", 2);
        sentiments.put( "beneficios", 2);
        sentiments.put( "mejor", 3);
        sentiments.put( "engaño", -3);
        sentiments.put( "mejor", 2);
        sentiments.put( "grande", 1);
        sentiments.put( "perra", -5);
        sentiments.put( "hembras", -5);
        sentiments.put( "extraño", -2);
        sentiments.put( "bla", -2);
        sentiments.put( "culpar", -2);
        sentiments.put( "bendiga", 2);
        sentiments.put( "a ciegas", -1);
        sentiments.put( "dicha", 3);
        sentiments.put( "bloque", -1);
        sentiments.put( "superproducción", 3);
        sentiments.put( "bloqueado", -1);
        sentiments.put( "bloques", -1);
        sentiments.put( "bloqueo", -1);
        sentiments.put( "sangrienta", -3);
        sentiments.put( "bomba", -1);
        sentiments.put( "aumentar", 1);
        sentiments.put( "sesión", 1);
        sentiments.put( "impulso", 1);
        sentiments.put( "aumenta", 1);
        sentiments.put( "cansado", -2);
        sentiments.put( "aburrido", -3);
        sentiments.put( "molestó", -2);
        sentiments.put( "boicot", -2);
        sentiments.put( "BOYCOT", -2);
        sentiments.put( "boicoteado", -2);
        sentiments.put( "boicot", -2);
        sentiments.put( "lavado de cerebro", -3);
        sentiments.put( "valiente", 2);
        sentiments.put( "fantástica", 5);
        sentiments.put( "avance", 3);
        sentiments.put( "soborno", -3);
        sentiments.put( "brillante", 4);
        sentiments.put( "rompió", -1);
        sentiments.put( "broked", -1);
        sentiments.put( "roto", -1);
        sentiments.put( "sin sentido", -4);
        sentiments.put( "intimidado", -2);
        sentiments.put( "bully", -2);
        sentiments.put( "bullying", -2);
        sentiments.put( "fastidio" ,-2);
        sentiments.put( "carga", -2);
        sentiments.put( "tranquila", 2);
        sentiments.put( "calmó", 2);
        sentiments.put( "suave", 2);
        sentiments.put( "calma", 2);
        sentiments.put( "cancelar", -1);
        sentiments.put( "cancelar", -1);
        sentiments.put( "cáncer", -1);
        sentiments.put( "cuidar", 2);
        sentiments.put( "sin preocupaciones", 1);
        sentiments.put( "precaución", 2);
        sentiments.put( "cuidado", 2);
        sentiments.put( "cuidar", 2);
        sentiments.put( "catastrófica", -4);
        sentiments.put( "redimir", -2);
        sentiments.put( "accidente", -2);
        sentiments.put( "celebrar", 3);
        sentiments.put( "celebra", 3);
        sentiments.put( "celebrar", 3);
        sentiments.put( "celebrar", 3);
        sentiments.put( "censurar", -2);
        sentiments.put( "censurado", -2);
        sentiments.put( "censura", -2);
        sentiments.put( "seguro", 1);
        sentiments.put( "desafío", -1);
        sentiments.put( "costos", -2);
        sentiments.put( "alegría", 2);
        sentiments.put( "alegre", 2);
        sentiments.put( "animando", 2);
        sentiments.put( "Cheers", 3);
        sentiments.put( "alegre", 3);
        sentiments.put( "enfriamiento", -1);
        sentiments.put( "aclara", 2);
        sentiments.put( "claridad", 2);
        sentiments.put( "choque", -2);
        sentiments.put( "limpia", 2);
        sentiments.put( "más limpia", 2);
        sentiments.put( "eliminar", 1);
        sentiments.put( "borra", 1);
        sentiments.put( "borra", 1);
        sentiments.put( "inteligente", 2);
        sentiments.put( "oportunidad", 2);
        sentiments.put( "posibilidades", 2);
        sentiments.put( "caos", -2);
        sentiments.put( "caótica", -2);
        sentiments.put( "cargado", -3);
        sentiments.put( "trampa", -3);
        sentiments.put( "tramposo", -3);
        sentiments.put( "tramposos", -3);
        sentiments.put( "trampa", -3);
        sentiments.put( "trampa", -3);
        sentiments.put( "alegría", 2);
        sentiments.put( "Cheers", 2);
        sentiments.put( "alegría", 2);
        sentiments.put( "acariciar", 2);
        sentiments.put( "protegido", 2);
        sentiments.put( "abriga", 2);
        sentiments.put( "acariciar", 2);
        sentiments.put( "ni idea", -2);
        sentiments.put( "gallo", -5);
        sentiments.put( "hijo de puta", -5);
        sentiments.put( "colapso", -2);
        sentiments.put( "derrumbó", -2);
        sentiments.put( "colapsa", -2);
        sentiments.put( "colapso", -2);
        sentiments.put( "chocar", -1);
        sentiments.put( "chocar", -1);
        sentiments.put( "chocar", -1);
        sentiments.put( "colisión", -2);
        sentiments.put( "colisiones", -2);
        sentiments.put( "conspirar", -3);
        sentiments.put( "batalla", -1);
        sentiments.put( "lucha", -1);
        sentiments.put( "alabanzas", 2);
        sentiments.put( "felicitó", 2);
        sentiments.put( "commit", 1);
        sentiments.put( "compromiso", 2);
        sentiments.put( "comprometida", 1);
        sentiments.put( "commit", 1);
        sentiments.put( "commit", 1);
        sentiments.put( "integral", 2);
        sentiments.put( "confianza", 2);
        sentiments.put( "conflicto", -2);
        sentiments.put( "conflicto", -2);
        sentiments.put( "conflictos", -2);
        sentiments.put( "confuso", -2);
        sentiments.put( "confunda", -2);
        sentiments.put( "confunde", -2);
        sentiments.put( "felicitaciones", 2);
        sentiments.put( "felicitar", 2);
        sentiments.put( "felicitaciones", 2);
        sentiments.put( "felicitaciones", 2);
        sentiments.put( "conspiración", -3);
        sentiments.put( "controvertido", -2);
        sentiments.put( "controvertido", -2);
        sentiments.put( "convencer", 1);
        sentiments.put( "convencido", 1);
        sentiments.put( "convence", 1);
        sentiments.put( "fresco", 1);
        sentiments.put( "igual", -1);
        sentiments.put( "costoso", -2);
        sentiments.put( "cortesía", 2);
        sentiments.put( "encubrimiento", -3);
        sentiments.put( "comodidad", 2);
        sentiments.put( "calambre", -1);
        sentiments.put( "basura", -3);
        sentiments.put( "Crash", -2);
        sentiments.put( "loco", -2);
        sentiments.put( "creativo", 2);
        sentiments.put( "grito", -2);
        sentiments.put( "crimen", -3);
        sentiments.put( "criminales", -3);
        sentiments.put( "criminales", -3);
        sentiments.put( "crisis", -3);
        sentiments.put( "crítico", -2);
        sentiments.put( "críticos", -2);
        sentiments.put( "criticar", -2);
        sentiments.put( "criticado", -2);
        sentiments.put( "criticar", -2);
        sentiments.put( "criticar", -2);
        sentiments.put( "cruel", -3);
        sentiments.put( "crueldad", -3);
        sentiments.put( "llorar", -1);
        sentiments.put( "llorando", -2);
        sentiments.put( "coño", -5);
        sentiments.put( "maldición", -1);
        sentiments.put( "cortar", -1);
        sentiments.put( "dulce", 2);
        sentiments.put( "cortes", -1);
        sentiments.put( "corte", -1);
        sentiments.put( "cinismo", -2);
        sentiments.put( "daño", -3);
        sentiments.put( "daños y perjuicios", -3);
        sentiments.put( "infierno", -4);
        sentiments.put( "maldito", -4);
        sentiments.put( "oscuro", -2);
        sentiments.put( "demostración", -1);
        sentiments.put( "peligro", -2);
        sentiments.put( "muerto", -3);
        sentiments.put( "punto muerto", -2);
        sentiments.put( "querida", 2);
        sentiments.put( "cara", 3);
        sentiments.put( "ensordecedor", -1);
        sentiments.put( "muerto", -2);
        sentiments.put( "deuda", -2);
        sentiments.put( "engañar", -3);
        sentiments.put( "engañado", -3);
        sentiments.put( "trampa", -3);
        sentiments.put( "engañar", -3);
        sentiments.put( "engaño", -3);
        sentiments.put( "defectuoso", -3);
        sentiments.put( "defectos", -3);
        sentiments.put( "defensor", 2);
        sentiments.put( "defensores", 2);
        sentiments.put( "posponer", -1);
        sentiments.put( "defering", -1);
        sentiments.put( "déficit", -2);
        sentiments.put( "retraso", -1);
        sentiments.put( "retrasa", -1);
        sentiments.put( "deleite", 3);
        sentiments.put( "emocionado", 3);
        sentiments.put( "se negó", -2);
        sentiments.put( "denier", -2);
        sentiments.put( "negacionistas", -2);
        sentiments.put( "negar", -2);
        sentiments.put( "condenar", -2);
        sentiments.put( "condenar", -2);
        sentiments.put( "rechazar", -2);
        sentiments.put( "rechazar", -2);
        sentiments.put( "deprimida", -2);
        sentiments.put( "presión", -2);
        sentiments.put( "descarrilar", -2);
        sentiments.put( "pistas", -2);
        sentiments.put( "mock", -2);
        sentiments.put( "ridiculizado", -2);
        sentiments.put( "mock", -2);
        sentiments.put( "ridiculizado", -2);
        sentiments.put( "deseo", 1);
        sentiments.put( "deseado", 2);
        sentiments.put( "burla", -2);
        sentiments.put( "desesperación", -3);
        sentiments.put( "desesperación", -3);
        sentiments.put( "desesperada", -3);
        sentiments.put( "desesperada", -3);
        sentiments.put( "destruir", -3);
        sentiments.put( "destruir", -3);
        sentiments.put( "roto", -3);
        sentiments.put( "destrucción", -3);
        sentiments.put( "sostener", -2);
        sentiments.put( "detenido", -2);
        sentiments.put( "custodia", -2);
        sentiments.put( "aplastado", -2);
        sentiments.put( "devastadora", -2);
        sentiments.put( "dedicado", 3);
        sentiments.put( "Dick", -4);
        sentiments.put( "idiota", -4);
        sentiments.put( "die", -3);
        sentiments.put( "muerto", -3);
        sentiments.put( "duro", -1);
        sentiments.put( "Dilema", -1);
        sentiments.put( "grave", -3);
        sentiments.put( "tierra", -2);
        sentiments.put( "sucia", -2);
        sentiments.put( "sucio", -2);
        sentiments.put( "sucia", -2);
        sentiments.put( "incapacitante", -1);
        sentiments.put( "desaparecer", -1);
        sentiments.put( "desaparecer", -1);
        sentiments.put( "desapareció", -1);
        sentiments.put( "cubo", -2);
        sentiments.put( "decepcionado", -2);
        sentiments.put( "decepcionante", -2);
        sentiments.put( "decepción", -2);
        sentiments.put( "decepción", -2);
        sentiments.put( "decepciona", -2);
        sentiments.put( "catástrofe", -2);
        sentiments.put( "desastres", -2);
        sentiments.put( "catastrófica", -3);
        sentiments.put( "falta de armonía", -2);
        sentiments.put( "disgusto", -3);
        sentiments.put( "repugnante", -3);
        sentiments.put( "deshonesto", -2);
        sentiments.put( "horrorizado", -2);
        sentiments.put( "diferencia", -2);
        sentiments.put( "disputa", -2);
        sentiments.put( "diferencias", -2);
        sentiments.put( "contendiente", -2);
        sentiments.put( "falta de respeto", -2);
        sentiments.put( "interrupción", -2);
        sentiments.put( "interferencia", -2);
        sentiments.put( "disruptiva", -2);
        sentiments.put( "pervertido", -2);
        sentiments.put( "distorsionada", -2);
        sentiments.put( "sesgo", -2);
        sentiments.put( "twist", -2);
        sentiments.put( "dissy", -1);
        sentiments.put( "distraer", -2);
        sentiments.put( "distraído", -2);
        sentiments.put( "distracción", -2);
        sentiments.put( "distracción", -2);
        sentiments.put( "desconfianza", -3);
        sentiments.put( "dithering", -2);
        sentiments.put( "poco fiable", -2);
        sentiments.put( "esquivando", -2);
        sentiments.put( "no funciona", -3);
        sentiments.put( "no les gusta", -2);
        sentiments.put( "Doom", -2);
        sentiments.put( "condenado", -2);
        sentiments.put( "duda", -1);
        sentiments.put( "duda", -1);
        sentiments.put( "lado negativo", -2);
        sentiments.put( "arrastre", -1);
        sentiments.put( "arrastre", -1);
        sentiments.put( "arrastrado", -1);
        sentiments.put( "temor", -2);
        sentiments.put( "sueño", 1);
        sentiments.put( "Sueños", 1);
        sentiments.put( "drop", -1);
        sentiments.put( "ahogar", -2);
        sentiments.put( "ahogada", -2);
        sentiments.put( "ahogamiento", -2);
        sentiments.put( "intoxicado", -2);
        sentiments.put( "dudosos", -2);
        sentiments.put( "fracaso", -2);
        sentiments.put( "estúpida", -3);
        sentiments.put( "dump", -1);
        sentiments.put( "objeto de dumping", -2);
        sentiments.put( "disfunción", -2);
        sentiments.put( "agudo", 2);
        sentiments.put( "luz", 2);
        sentiments.put( "siniestro", -2);
        sentiments.put( "siniestro", -2);
        sentiments.put( "eficaz", 2);
        sentiments.put( "eficaz", 2);
        sentiments.put( "vergüenza", -2);
        sentiments.put( "vergüenza", -2);
        sentiments.put( "vergüenza", -2);
        sentiments.put( "embarazosa", -2);
        sentiments.put( "abrazar", 1);
        sentiments.put( "emergencia", -2);
        sentiments.put( "alentador", 2);
        sentiments.put( "animar", 2);
        sentiments.put( "animó", 2);
        sentiments.put( "avala", 2);
        sentiments.put( "dejar de fumar", 2);
        sentiments.put( "avala", 2);
        sentiments.put( "respaldo", 2);
        sentiments.put( "enemigos", -2);
        sentiments.put( "enemigo", -2);
        sentiments.put( "comprometer", 1);
        sentiments.put( "comprometer", 1);
        sentiments.put( "disfrutar", 2);
        sentiments.put( "tiene", 2);
        sentiments.put( "disfrutando", 2);
        sentiments.put( "esclarecedor", 2);
        sentiments.put( "esclavo", -2);
        sentiments.put( "esclavizado", -2);
        sentiments.put( "esclaviza", -2);
        sentiments.put( "seguro", 1);
        sentiments.put( "seguro", 1);
        sentiments.put( "entretenida", 2);
        sentiments.put( "envidia", -1);
        sentiments.put( "envidia", -1);
        sentiments.put( "envidiada", -1);
        sentiments.put( "escate", -1);
        sentiments.put( "escates", -1);
        sentiments.put( "escating", -1);
        sentiments.put( "ética", 2);
        sentiments.put( "desalojo", -1);
        sentiments.put( "mal", -3);
        sentiments.put( "sobremarcha", -2);
        sentiments.put( "exagerada", -2);
        sentiments.put( "exagerando", -2);
        sentiments.put( "exagerando", -2);
        sentiments.put( "excelencia", 3);
        sentiments.put( "excelente", 3);
        sentiments.put( "tensa", 3);
        sentiments.put( "tensión", 3);
        sentiments.put( "emocionante", 3);
        sentiments.put( "excluye", -1);
        sentiments.put( "excluidos", -2);
        sentiments.put( "cortado", -1);
        sentiments.put( "exclusivo", 2);
        sentiments.put( "excusa", -1);
        sentiments.put( "agotado", -2);
        sentiments.put( "expandir", 1);
        sentiments.put( "expandir", 1);
        sentiments.put( "expulsar", -2);
        sentiments.put( "expulsa", -2);
        sentiments.put( "expulsado", -2);
        sentiments.put( "expulsar", -2);
        sentiments.put( "apalancamiento", -2);
        sentiments.put( "explotado", -2);
        sentiments.put( "exploits", -2);
        sentiments.put( "apalancamiento", -2);
        sentiments.put( "exponer", -1);
        sentiments.put( "expuesta", -1);
        sentiments.put( "exponer", -1);
        sentiments.put( "posponer", -1);
        sentiments.put( "expandir", 1);
        sentiments.put( "estiramiento", 1);
        sentiments.put( "fabulosa", 4);
        sentiments.put( "facinate", 3);
        sentiments.put( "fascinado", 3);
        sentiments.put( "fascinante", 3);
        sentiments.put( "moda", -2);
        sentiments.put( "marica", -3);
        sentiments.put( "maricones", -3);
        sentiments.put( "fail", -2);
        sentiments.put( "no", -2);
        sentiments.put( "fail", -2);
        sentiments.put( "defecto", -2);
        sentiments.put( "fracaso", -2);
        sentiments.put( "fiel", 3);
        sentiments.put( "justo", 2);
        sentiments.put( "fe", 1);
        sentiments.put( "falsa", -3);
        sentiments.put( "falsificaciones", -3);
        sentiments.put( "falsa", -3);
        sentiments.put( "caída", -1);
        sentiments.put( "Forge", -3);
        sentiments.put( "falsificado", -3);
        sentiments.put( "fama", 1);
        sentiments.put( "fan", 3);
        sentiments.put( "fantástica", 4);
        sentiments.put( "farsa", -1);
        sentiments.put( "fascista", -2);
        sentiments.put( "fascistas", -2);
        sentiments.put( "muertes", -3);
        sentiments.put( "muertes", -3);
        sentiments.put( "favor", 2);
        sentiments.put( "favorecer", 2);
        sentiments.put( "favorito", 2);
        sentiments.put( "favoritos", 2);
        sentiments.put( "favorito", 2);
        sentiments.put( "miedo", -2);
        sentiments.put( "horrible", -2);
        sentiments.put( "miedo", -2);
        sentiments.put( "Fearless", 2);
        sentiments.put( "cagar cansado", -3);
        sentiments.put( "débil", -2);
        sentiments.put( "sensación", 1);
        sentiments.put( "débil", -2);
        sentiments.put( "crimen", -3);
        sentiments.put( "crimen", -3);
        sentiments.put( "fiasco", -3);
        sentiments.put( "lucha", -1);
        sentiments.put( "agradable", 2);
        sentiments.put( "fuego", -2);
        sentiments.put( "disparado", -2);
        sentiments.put( "disparar", -2);
        sentiments.put( "fitness", 1);
        sentiments.put( "insignia", 2);
        sentiments.put( "huyendo", -1);
        sentiments.put( "Flop", -2);
        sentiments.put( "flop", -2);
        sentiments.put( "gripe", -2);
        sentiments.put( "tonto", -2);
        sentiments.put( "tontos", -2);
        sentiments.put( "olvidar", -1);
        sentiments.put( "olvidadizos", -2);
        sentiments.put( "olvidado", -1);
        sentiments.put( "frenética", -1);
        sentiments.put( "fraude", -4);
        sentiments.put( "estafador", -4);
        sentiments.put( "pícaros", -4);
        sentiments.put( "fraudulenta", -4);
        sentiments.put( "libre", 1);
        sentiments.put( "frenesí", -3);
        sentiments.put( "fresco", 1);
        sentiments.put( "amigable", 2);
        sentiments.put( "asustado", -2);
        sentiments.put( "frikin", -2);
        sentiments.put( "frustración", -2);
        sentiments.put( "ftw", 3);
        sentiments.put( "fuck", -4);
        sentiments.put( "jodido", -4);
        sentiments.put( "hijos de puta", -4);
        sentiments.put( "puta", -4);
        sentiments.put( "FUD", -3);
        sentiments.put( "cumplir", 2);
        sentiments.put( "cumplido", 2);
        sentiments.put( "cumplir", 2);
        sentiments.put( "diversión", 4);
        sentiments.put( "funeral", -1);
        sentiments.put( "original", 2);
        sentiments.put( "divertida", 4);
        sentiments.put( "furiosa", -3);
        sentiments.put( "granizo", 2);
        sentiments.put( "aclamado", 2);
        sentiments.put( "Hell", -4);
        sentiments.put( "ayuda", 2);
        sentiments.put( "ayudar", 2);
        sentiments.put( "impotencia", -2);
        sentiments.put( "ayudante", 2);
        sentiments.put( "héroe", 2);
        sentiments.put( "Héroes", 2);
        sentiments.put( "heroica", 3);
        sentiments.put( "Hambre", -2);
        sentiments.put( "dolor", -2);
        sentiments.put( "dolor", -2);
        sentiments.put( "dolor", -2);
        sentiments.put( "gag", -2);
        sentiments.put( "amordazada", -2);
        sentiments.put( "get", 2);
        sentiments.put( "got", 2);
        sentiments.put( "get", 2);
        sentiments.put( "ganancias", 2);
        sentiments.put( "fantasma", -1);
        sentiments.put( "feliz", 3);
        sentiments.put( "oscuridad", -1);
        sentiments.put( "brillante", 2);
        sentiments.put( "dios", 1);
        sentiments.put( "puta", -3);
        sentiments.put( "bueno", 3);
        sentiments.put( "gracia", 1);
        sentiments.put( "gran", 3);
        sentiments.put( "subvención", 1);
        sentiments.put( "concedida", 1);
        sentiments.put( "Acuerdo", 1);
        sentiments.put( "donaciones", 1);
        sentiments.put( "agradecido", 3);
        sentiments.put( "grave", -2);
        sentiments.put( "gris", -1);
        sentiments.put( "grande", 3);
        sentiments.put( "mayor", 3);
        sentiments.put( "el más grande", 3);
        sentiments.put( "avaricia", -3);
        sentiments.put( "lavado verde", -3);
        sentiments.put( "lavado verde", -3);
        sentiments.put( "lavado verde", -3);
        sentiments.put( "lavado verde", -3);
        sentiments.put( "lavado verde", -3);
        sentiments.put( "lavado verde", -3);
        sentiments.put( "saludar", 1);
        sentiments.put( "saludo", 1);
        sentiments.put( "saludar", 1);
        sentiments.put( "saludo", 1);
        sentiments.put( "saludos", 2);
        sentiments.put( "gris", -1);
        sentiments.put( "dolor", -2);
        sentiments.put( "bruto", -2);
        sentiments.put( "crecimiento", 1);
        sentiments.put( "culpabilidad", -3);
        sentiments.put( "culpable", -3);
        sentiments.put( "pistola", -1);
        sentiments.put( "hackeado", -1);
        sentiments.put( "felicidad", 3);
        sentiments.put( "feliz", 3);
        sentiments.put( "duro", -1);
        sentiments.put( "daño", -2);
        sentiments.put( "dañado", -2);
        sentiments.put( "perjudicial", -2);
        sentiments.put( "daño", -2);
        sentiments.put( "daños y perjuicios", -2);
        sentiments.put( "odio", -3);
        sentiments.put( "castigar", -1);
        sentiments.put( "Haunted", -2);
        sentiments.put( "guaridas", -1);
        sentiments.put( "inquietante", 1);
        sentiments.put( "destrucción", -2);
        sentiments.put( "sano", 2);
        sentiments.put( "corazón roto", -3);
        sentiments.put( "ayuda", 2);
        sentiments.put( "marca", 2);
        sentiments.put( "alegre", 2);
        sentiments.put( "engaño", -2);
        sentiments.put( "honesta", 2);
        sentiments.put( "esperanza", 2);
        sentiments.put( "esperanzador", 2);
        sentiments.put( "ojalá", 2);
        sentiments.put( "sin esperanza", -2);
        sentiments.put( "desesperanza", -2);
        sentiments.put( "esperanza", 2);
        sentiments.put( "esperanza", 2);
        sentiments.put( "honor", 2);
        sentiments.put( "honor", 2);
        sentiments.put( "horrible", -3);
        sentiments.put( "horrible", -3);
        sentiments.put( "hostil", -2);
        sentiments.put( "abrazo", 2);
        sentiments.put( "comprime", 2);
        sentiments.put( "grande", 1);
        sentiments.put( "vendedor ambulante", -2);
        sentiments.put( "humerous", 3);
        sentiments.put( "humor", 3);
        sentiments.put( "humor", 3);
        sentiments.put( "Cheers", 5);
        sentiments.put( "Hambre", -2);
        sentiments.put( "histeria", -3);
        sentiments.put( "crecimiento", 2);
        sentiments.put( "idiota", -3);
        sentiments.put( "idiota", -3);
        sentiments.put( "ignorancia", -2);
        sentiments.put( "ignorar", -1);
        sentiments.put( "ignorar", -1);
        sentiments.put( "ignorado", -2);
        sentiments.put( "enfermo", -2);
        sentiments.put( "ilegal", -3);
        sentiments.put( "analfabetismo", -2);
        sentiments.put( "enfermedad", -2);
        sentiments.put( "enfermedades", -2);
        sentiments.put( "imperfecto", -2);
        sentiments.put( "significado", 2);
        sentiments.put( "importante", 2);
        sentiments.put( "imponer", -1);
        sentiments.put( "impuesta", -1);
        sentiments.put( "impone", -1);
        sentiments.put( "impresionante", -1);
        sentiments.put( "impotente", -2);
        sentiments.put( "impresionar", 3);
        sentiments.put( "impresionado", 3);
        sentiments.put( "impresiona", 3);
        sentiments.put( "impresionante", 3);
        sentiments.put( "mejorar", 2);
        sentiments.put( "mejora", 2);
        sentiments.put( "mejorado", 2);
        sentiments.put( "mejora", 2);
        sentiments.put( "mejorar", 2);
        sentiments.put( "incapacidad", -2);
        sentiments.put( "inacción", -2);
        sentiments.put( "inadecuada", -2);
        sentiments.put( "incompetencia", -2);
        sentiments.put( "práctico", -2);
        sentiments.put( "aumentar", 1);
        sentiments.put( "sesión", 1);
        sentiments.put( "indiferente", -2);
        sentiments.put( "indignación", -2);
        sentiments.put( "adoctrinar", -2);
        sentiments.put( "adoctrinados", -2);
        sentiments.put( "adoctrina", -2);
        sentiments.put( "adoctrinar", -2);
        sentiments.put( "ineficaz", -2);
        sentiments.put( "ineficaz",-2);
        sentiments.put( "violación", -2);
        sentiments.put( "enfurecer", -2);
        sentiments.put( "enfurece", -2);
        sentiments.put( "inhibir", -1);
        sentiments.put( "daño", -2);
        sentiments.put( "la injusticia", -2);
        sentiments.put( "innovar", 1);
        sentiments.put( "innova", 1);
        sentiments.put( "innovación", 1);
        sentiments.put( "Inquisición", -2);
        sentiments.put( "loco", -2);
        sentiments.put( "demencia", -2);
        sentiments.put( "insensibilidad", -2);
        sentiments.put( "insípida", -2);
        sentiments.put( "inspiración", 2);
        sentiments.put( "inspirador", 2);
        sentiments.put( "inspirar", 2);
        sentiments.put( "inspiraciones", 2);
        sentiments.put( "inspirar", 3);
        sentiments.put( "intacta", 2);
        sentiments.put( "integridad", 2);
        sentiments.put( "intensa", 1);
        sentiments.put( "interés", 1);
        sentiments.put( "intereses", 1);
        sentiments.put( "interesado", 2);
        sentiments.put( "interesante", 2);
        sentiments.put( "cancelar", -2);
        sentiments.put( "cancelado", -2);
        sentiments.put( "cancelar", -2);
        sentiments.put( "abortar", -2);
        sentiments.put( "interrupción", -2);
        sentiments.put( "asustar", -2);
        sentiments.put( "asustado", -2);
        sentiments.put( "aterradora", -2);
        sentiments.put( "aterradora", -2);
        sentiments.put( "invitar", 1);
        sentiments.put( "irracional", -1);
        sentiments.put( "irreversible", -1);
        sentiments.put( "ironía", -1);
        sentiments.put( "irónico", -1);
        sentiments.put( "Jackass", -4);
        sentiments.put( "tirones", -4);
        sentiments.put( "cárcel", -2);
        sentiments.put( "peligro", -2);
        sentiments.put( "idiota", -3);
        sentiments.put( "Jesús", 1);
        sentiments.put( "Stay", 1);
        sentiments.put( "broma", 2);
        sentiments.put( "alegría", 3);
        sentiments.put( "justicia", 2);
        sentiments.put( "recta", 2);
        sentiments.put( "matar", -3);
        sentiments.put( "matar", -3);
        sentiments.put( "matar", -3);
        sentiments.put( "clase", 2);
        sentiments.put( "beso", 2);
        sentiments.put( "felicitaciones", 3);
        sentiments.put( "defecto", -2);
        sentiments.put( "dilación", -1);
        sentiments.put( "lag", -2);
        sentiments.put( "retraso", -2);
        sentiments.put( "retraso", -2);
        sentiments.put( "lame", -2);
        sentiments.put( "referencia", 2);
        sentiments.put( "reírse", 1);
        sentiments.put( "reírse", 1);
        sentiments.put( "reírse", 1);
        sentiments.put( "marcha", 1);
        sentiments.put( "demanda", -2);
        sentiments.put( "acción", -2);
        sentiments.put( "fuga", -1);
        sentiments.put( "filtrado", -1);
        sentiments.put( "dejar", -1);
        sentiments.put( "legales", 1);
        sentiments.put( "legales", 1);
        sentiments.put( "mentiroso", -3);
        sentiments.put( "mentirosos", -3);
        sentiments.put( "injurioso", -2);
        sentiments.put( "mintió", -2);
        sentiments.put( "quién", 2);
        sentiments.put( "le gusta", 2);
        sentiments.put( "le gusta", 2);
        sentiments.put( "restringida", -1);
        sentiments.put( "límites", -1);
        sentiments.put( "limitación", -1);
        sentiments.put( "litigio", -1);
        sentiments.put( "viva", 2);
        sentiments.put( "lobby", -2);
        sentiments.put( "lobby", -2);
        sentiments.put( "lol", 3);
        sentiments.put( "solitario", -2);
        sentiments.put( "telar", -1);
        sentiments.put( "surgió", -1);
        sentiments.put( "terror", -1);
        sentiments.put( "telares", -1);
        sentiments.put( "suelto", -3);
        sentiments.put( "señor", -3);
        sentiments.put( "perder", -3);
        sentiments.put( "pérdida", -3);
        sentiments.put( "Lost", -3);
        sentiments.put( "amor", 3);
        sentiments.put( "preciosa", 3);
        sentiments.put( "bajo", -1);
        sentiments.put( "infierno", 3);
        sentiments.put( "loco", -3);
        sentiments.put( "loco", -3);
        sentiments.put( "maravilla", -1);
        sentiments.put( "maravilla", -1);
        sentiments.put( "maravilla", -1);
        sentiments.put( "loco", -3);
        sentiments.put( "compuesta", -1);
        sentiments.put( "locamente", -3);
        sentiments.put( "locura", -3);
        sentiments.put( "obligatoria", -1);
        sentiments.put( "manipulada", -1);
        sentiments.put( "manipular", -1);
        sentiments.put( "manipulación", -1);
        sentiments.put( "lo que sea", 1);
        sentiments.put( "casos", 1);
        sentiments.put( "significativa", 2);
        sentiments.put( "sin sentido", -2);
        sentiments.put( "medalla", 3);
        sentiments.put( "misericordia", 2);
        sentiments.put( "raíz", -2);
        sentiments.put( "mal estado", -2);
        sentiments.put( "empuje", -2);
        sentiments.put( "sin sentido", -2);
        sentiments.put( "miseria", -2);
        sentiments.put( "engañosa", -3);
        sentiments.put( "accidentes", -2);
        sentiments.put( "travesura", -2);
        sentiments.put( "males", -2);
        sentiments.put( "información errónea", -2);
        sentiments.put( "mal informado", -2);
        sentiments.put( "malinterpretado", -1);
        sentiments.put( "Informe de errores", -2);
        sentiments.put( "se perdió", -2);
        sentiments.put( "error", -2);
        sentiments.put( "error", -2);
        sentiments.put( "error", -2);
        sentiments.put( "confundir", -2);
        sentiments.put( "mongering", -2);
        sentiments.put( "monopolizar", -2);
        sentiments.put( "hijo de puta", -5);
        sentiments.put( "puta", -5);
        sentiments.put( "asesinato", -2);
        sentiments.put( "asesino", -2);
        sentiments.put( "mito", -1);
        sentiments.put( "feo", -3);
        sentiments.put( "negativo", -2);
        sentiments.put( "mala conducta", -2);
        sentiments.put( "descuidado", -2);
        sentiments.put( "abandono", -2);
        sentiments.put( "descuidado", -2);
        sentiments.put( "nervios", -1);
        sentiments.put( "nervioso", -2);
        sentiments.put( "agradable", 3);
        sentiments.put( "ingenioso", 2);
        sentiments.put( "negro", -5);
        sentiments.put( "no", -1);
        sentiments.put( "no", -1);
        sentiments.put( "no es divertido", -3);
        sentiments.put( "nobles", 2);
        sentiments.put( "sin sentido", -2);
        sentiments.put( "no es bueno", -2);
        sentiments.put( "novela", 2);
        sentiments.put( "notoria", -2);
        sentiments.put( "no trabajar", -3);
        sentiments.put( "frutos secos", -3);
        sentiments.put( "blot", -2);
        sentiments.put( "aniquilado", -2);
        sentiments.put( "obscenas", -2);
        sentiments.put( "fuera de línea", -1);
        sentiments.put( "obsoleta", -2);
        sentiments.put( "obstáculo", -2);
        sentiments.put( "obstáculos", -2);
        sentiments.put( "insulto", -2);
        sentiments.put( "ofendido", -2);
        sentiments.put( "delincuente", -2);
        sentiments.put( "inaceptable", -2);
        sentiments.put( "insultos", -2);
        sentiments.put( "buey", 2);
        sentiments.put( "siniestro", 3);
        sentiments.put( "oportunidad", 2);
        sentiments.put( "oportunidades", 2);
        sentiments.put( "optimismo", 2);
        sentiments.put( "chocante", -3);
        sentiments.put( "furiosa", -3);
        sentiments.put( "extensión", 2);
        sentiments.put( "sobresaliente", 5);
        sentiments.put( "sobrecarga", -1);
        sentiments.put( "reaccionar de forma exagerada", -2);
        sentiments.put( "exagerando", -2);
        sentiments.put( "reacción exagerada", -2);
        sentiments.put( "exagerar", -2);
        sentiments.put( "sobreventa", -2);
        sentiments.put( "oversells", -2);
        sentiments.put( "simplificación", -2);
        sentiments.put( "simplificada", -2);
        sentiments.put( "simplifica", -2);
        sentiments.put( "simplificar", -2);
        sentiments.put( "exceso de peso", -1);
        sentiments.put( "contradicción", -1);
        sentiments.put( "dolor", -2);
        sentiments.put( "pánico", -3);
        sentiments.put( "paradoja", -1);
        sentiments.put( "parlamento", -1);
        sentiments.put( "patética", -2);
        sentiments.put( "pagar", -1);
        sentiments.put( "paz", 2);
        sentiments.put( "pacífica", 2);
        sentiments.put( "pacífica", 2);
        sentiments.put( "castigo", -2);
        sentiments.put( "perfecta", 3);
        sentiments.put( "perfectos", 2);
        sentiments.put( "perfeccionado", 2);
        sentiments.put( "perfecta", 3);
        sentiments.put( "peligro", -2);
        sentiments.put( "falso testimonio", -3);
        sentiments.put( "autor", -2);
        sentiments.put( "autores", -2);
        sentiments.put( "pesimismo", -2);
        sentiments.put( "pintoresco", 2);
        sentiments.put( "pis", -4);
        sentiments.put( "molesto", -4);
        sentiments.put( "compasión", -2);
        sentiments.put( "agradable", 3);
        sentiments.put( "por favor", 1);
        sentiments.put( "satisfecho", 3);
        sentiments.put( "listo", -2);
        sentiments.put( "casado", -2);
        sentiments.put( "envenenado", -2);
        sentiments.put( "venenos", -2);
        sentiments.put( "contaminar", -2);
        sentiments.put( "contaminar", -2);
        sentiments.put( "contaminado", -2);
        sentiments.put( "contamina", -2);
        sentiments.put( "contaminadores", -2);
        sentiments.put( "popular", 3);
        sentiments.put( "malo", -2);
        sentiments.put( "peor", -2);
        sentiments.put( "pobre", -2);
        sentiments.put( "positivo", 2);
        sentiments.put( "positivo", 2);
        sentiments.put( "posponer", -1);
        sentiments.put( "diferido", -1);
        sentiments.put( "exponer", -1);
        sentiments.put( "posponer", -1);
        sentiments.put( "la pobreza", -1);
        sentiments.put( "alabanza", 3);
        sentiments.put( "felicitó", 3);
        sentiments.put( "Pras", 3);
        sentiments.put( "glorificando", 3);
        sentiments.put( "petición", 1);
        sentiments.put( "pedir", 1);
        sentiments.put( "pedir", 1);
        sentiments.put( "prblm", -2);
        sentiments.put( "prblms", -2);
        sentiments.put( "prepaired", 1);
        sentiments.put( "presión", -1);
        sentiments.put( "perezosa", -1);
        sentiments.put( "hojas", -1);
        sentiments.put( "perezosa", -1);
        sentiments.put( "bonita", 1);
        sentiments.put( "prevenir", -1);
        sentiments.put( "impedido", -1);
        sentiments.put( "prevenir", -1);
        sentiments.put( "prevenir", -1);
        sentiments.put( "picadura", -5);
        sentiments.put( "problema", -2);
        sentiments.put( "problemas", -2);
        sentiments.put( "aprovechado", -2);
        sentiments.put( "progreso", 2);
        sentiments.put( "elevación", 1);
        sentiments.put( "prometió", 1);
        sentiments.put( "leyes", 1);
        sentiments.put( "promoción", 1);
        sentiments.put( "promovido", 1);
        sentiments.put( "promover", 1);
        sentiments.put( "promoción", 1);
        sentiments.put( "propaganda", -2);
        sentiments.put( "procesar", -1);
        sentiments.put( "procesado", -2);
        sentiments.put( "perseguidor", -1);
        sentiments.put( "procesamiento", -1);
        sentiments.put( "Folleto", 1);
        sentiments.put( "perspectivas", 1);
        sentiments.put( "próspero", 3);
        sentiments.put( "proteger", 1);
        sentiments.put( "protegido", 1);
        sentiments.put( "protector", 1);
        sentiments.put( "protesta", -2);
        sentiments.put( "manifestantes", -2);
        sentiments.put( "protestas", -2);
        sentiments.put( "protestó", -2);
        sentiments.put( "orgullo", 2);
        sentiments.put( "orgullo", 2);
        sentiments.put( "pseudociencia", -3);
        sentiments.put( "castigar", -2);
        sentiments.put( "sanciones", -2);
        sentiments.put( "punitivo", -2);
        sentiments.put( "signo de interrogación", -1);
        sentiments.put( "lluvia", -1);
        sentiments.put( "diatriba", -3);
        sentiments.put( "diatribas", -3);
        sentiments.put( "diatribas", -3);
        sentiments.put( "Charlatanes", -3);
        sentiments.put( "violación", -4);
        sentiments.put( "rash", -2);
        sentiments.put( "ahora", 1);
        sentiments.put( "cuando", 1);
        sentiments.put( "alcanzó", 1);
        sentiments.put( "alcanzó", 1);
        sentiments.put( "recomendar", 2);
        sentiments.put( "recomienda", 2);
        sentiments.put( "recomendar", 2);
        sentiments.put( "rechazar", -2);
        sentiments.put( "se negó", -2);
        sentiments.put( "rechazar", -2);
        sentiments.put( "deshacer", -2);
        sentiments.put( "rechazo", -1);
        sentiments.put( "rechazada", -1);
        sentiments.put( "rechaza", -1);
        sentiments.put( "rechazo", -1);
        sentiments.put( "alegran", 4);
        sentiments.put( "regocijo", 4);
        sentiments.put( "Cheers", 4);
        sentiments.put( "estúpida", -4);
        sentiments.put( "deleite", 4);
        sentiments.put( "S impresionante", 4);
        sentiments.put( "relajado", 2);
        sentiments.put( "notable", 2);
        sentiments.put( "rescate", 2);
        sentiments.put( "rescatado", 2);
        sentiments.put( "rescates", 2);
        sentiments.put( "retirarse", -1);
        sentiments.put( "renunció", -1);
        sentiments.put( "retirarse", -1);
        sentiments.put( "renuncia", -1);
        sentiments.put( "suelto", 2);
        sentiments.put( "resuelto", 2);
        sentiments.put( "fija", 2);
        sentiments.put( "suelto", 2);
        sentiments.put( "responsable", 2);
        sentiments.put( "Restless", -2);
        sentiments.put( "restaurar", 1);
        sentiments.put( "restaurado", 1);
        sentiments.put( "restaurar", 1);
        sentiments.put( "recupera", 1);
        sentiments.put( "límite", -2);
        sentiments.put( "restringida", -2);
        sentiments.put( "límite", -2);
        sentiments.put( "límite", -2);
        sentiments.put( "restricción", -2);
        sentiments.put( "retenido", -1);
        sentiments.put( "retardado", -2);
        sentiments.put( "revivir", 2);
        sentiments.put( "revive", 2);
        sentiments.put( "recompensa", 2);
        sentiments.put( "recompensado", 2);
        sentiments.put( "recompensa", 2);
        sentiments.put( "recompensas", 2);
        sentiments.put( "rico", 2);
        sentiments.put( "ridícula", -3);
        sentiments.put( "dirección correcta", 3);
        sentiments.put( "plataforma", -1);
        sentiments.put( "amañado", -1);
        sentiments.put( "estricta", 3);
        sentiments.put( "estrictamente", 3);
        sentiments.put( "disturbios", -2);
        sentiments.put( "disturbios", -2);
        sentiments.put( "riesgo", -2);
        sentiments.put( "riesgos", -2);
        sentiments.put( "Rob", -2);
        sentiments.put( "vestida", -2);
        sentiments.put( "roba", -2);
        sentiments.put( "robando", -2);
        sentiments.put( "ruina", -2);
        sentiments.put( "destruir", -2);
        sentiments.put( "sabotaje", -2);
        sentiments.put( "triste", -2);
        sentiments.put( "triste", -2);
        sentiments.put( "triste", -2);
        sentiments.put( "desgraciadamente", -2);
        sentiments.put( "ñoño", -1);
        sentiments.put( "sarcástica", -2);
        sentiments.put( "satisfecho", 2);
        sentiments.put( "Guardar", 2);
        sentiments.put( "rescatado", 2);
        sentiments.put( "fraude", -2);
        sentiments.put( "fraude", -2);
        sentiments.put( "escándalo", -3);
        sentiments.put( "escandalosa", -3);
        sentiments.put( "escándalos", -3);
        sentiments.put( "cabeza de turco", -2);
        sentiments.put( "cabezas de turco", -2);
        sentiments.put( "asustar", -2);
        sentiments.put( "miedo", -2);
        sentiments.put( "escéptico", -2);
        sentiments.put( "escépticos", -2);
        sentiments.put( "cuchara", 3);
        sentiments.put( "atornillado", -2);
        sentiments.put( "metió la pata", -3);
        sentiments.put( "seguro", 2);
        sentiments.put( "asegurada", 2);
        sentiments.put( "garantizar", 2);
        sentiments.put( "engañado", -1);
        sentiments.put( "egoísta", -3);
        sentiments.put( "egoísmo", -3);
        sentiments.put( "sentencia", -2);
        sentiments.put( "condenado", -2);
        sentiments.put( "sentencia", -2);
        sentiments.put( "frases", -2);
        sentiments.put( "sexy", 3);
        sentiments.put( "inestable", -2);
        sentiments.put( "La vergüenza", -2);
        sentiments.put( "vergonzosa", -2);
        sentiments.put( "valores", 1);
        sentiments.put( "acciones", 1);
        sentiments.put( "compartida", 1);
        sentiments.put( "musaraña", -4);
        sentiments.put( "mierda", -4);
        sentiments.put( "imbécil", -4);
        sentiments.put( "mierda", -3);
        sentiments.put( "choque", -2);
        sentiments.put( "choque", -2);
        sentiments.put( "conmocionado", -2);
        sentiments.put( "chocante", -2);
        sentiments.put( "disparar", -1);
        sentiments.put( "miope", -2);
        sentiments.put( "corto de vista", -2);
        sentiments.put( "escasez", -2);
        sentiments.put( "escasez", -2);
        sentiments.put( "tímido", -1);
        sentiments.put( "enfermo", -2);
        sentiments.put( "suspiro", -2);
        sentiments.put( "estúpida", -2);
        sentiments.put( "silencio", -1);
        sentiments.put( "pecado", -3);
        sentiments.put( "corto de miras", -2);
        sentiments.put( "escéptico", -2);
        sentiments.put( "escépticos", -2);
        sentiments.put( "escepticismo", -2);
        sentiments.put( "lodo", -2);
        sentiments.put( "barra", -2);
        sentiments.put( "cortar", -2);
        sentiments.put( "barras", -2);
        sentiments.put( "roza", -2);
        sentiments.put( "insomnio", -2);
        sentiments.put( "zorra", -5);
        sentiments.put( "inteligente", 1);
        sentiments.put( "mancha", -2);
        sentiments.put( "sonrisa", 2);
        sentiments.put( "sonrisa", 2);
        sentiments.put( "niebla", -2);
        sentiments.put( "chata", -2);
        sentiments.put( "desaires", -2);
        sentiments.put( "aleccionador", 1);
        sentiments.put( "sólida", 2);
        sentiments.put( "Solidaridad", 2);
        sentiments.put( "solución", 1);
        sentiments.put( "soluciones", 1);
        sentiments.put( "suelto", 1);
        sentiments.put( "resuelto", 1);
        sentiments.put( "fija", 1);
        sentiments.put( "suelto", 1);
        sentiments.put( "una especie de", 0);
        sentiments.put( "huérfanos", -5);
        sentiments.put( "dolor", -1);
        sentiments.put( "lo siento", -1);
        sentiments.put( "chispa", 1);
        sentiments.put( "chispa", 3);
        sentiments.put( "destellos", 3);
        sentiments.put( "espumoso", 3);
        sentiments.put( "espíritu", 1);
        sentiments.put( "puñalada", -2);
        sentiments.put( "picado", -2);
        sentiments.put( "estable", 2);
        sentiments.put( "pegue", -2);
        sentiments.put( "parada", -2);
        sentiments.put( "detuvo", -2);
        sentiments.put( "estancamiento", -2);
        sentiments.put( "morir de hambre", -2);
        sentiments.put( "muerto de hambre", -2);
        sentiments.put( "morir de hambre", -2);
        sentiments.put( "morir de hambre", -2);
        sentiments.put( "robar", -2);
        sentiments.put( "robar", -2);
        sentiments.put( "estimulante", 1);
        sentiments.put( "estimulada", 1);
        sentiments.put( "estimular", 1);
        sentiments.put( "estimulante", 2);
        sentiments.put( "robado", -2);
        sentiments.put( "stop", -1);
        sentiments.put( "stop", -1);
        sentiments.put( "detuvo", -1);
        sentiments.put( "stop", -1);
        sentiments.put( "extraña", -1);
        sentiments.put( "estrangulada", -2);
        sentiments.put( "fuerza", 2);
        sentiments.put( "fuerza", 2);
        sentiments.put( "fuerza", 2);
        sentiments.put( "fortalecida", 2);
        sentiments.put( "fuerzas", 2);
        sentiments.put( "paro", -1);
        sentiments.put( "huelguistas", -2);
        sentiments.put( "paro", -1);
        sentiments.put( "fuerte", 2);
        sentiments.put( "fuerte", 2);
        sentiments.put( "fuerte", 2);
        sentiments.put( "impresionante", 4);
        sentiments.put( "estúpida", -2);
        sentiments.put( "éxito", 2);
        sentiments.put( "éxito", 3);
        sentiments.put( "sufrir", -2);
        sentiments.put( "sufrimiento", -2);
        sentiments.put( "suicidio", -2);
        sentiments.put( "Sue", -2);
        sentiments.put( "el mal humor", -2);
        sentiments.put( "sol", 2);
        sentiments.put( "super", 3);
        sentiments.put( "excelente", 5);
        sentiments.put( "apoyo", 2);
        sentiments.put( "compatible", 2);
        sentiments.put( "adherente", 1);
        sentiments.put( "seguidores", 1);
        sentiments.put( "apoyo", 2);
        sentiments.put( "apoyo", 2);
        sentiments.put( "sobrevivió", 2);
        sentiments.put( "sobreviviente", 2);
        sentiments.put( "Survivor", 2);
        sentiments.put( "sospechar", -1);
        sentiments.put( "sospechar", -1);
        sentiments.put( "sospechar", -1);
        sentiments.put( "sospechosos", -1);
        sentiments.put( "suspender", -1);
        sentiments.put( "suspendido", -1);
        sentiments.put( "estampida", -2);
        sentiments.put( "recta", 1);
        sentiments.put( "factor de estrés", -2);
        sentiments.put( "factores de estrés", -2);
        sentiments.put( "paro", -2);
        sentiments.put( "significativo", 1);
        sentiments.put( "chupar", -3);
        sentiments.put( "chupa", -3);
        sentiments.put( "sufrir", -2);
        sentiments.put( "sufrimiento", -2);
        sentiments.put( "apoyo", 1);
        sentiments.put( "compatible", 1);
        sentiments.put( "apoyo", 1);
        sentiments.put( "apoyo", 1);
        sentiments.put( "dulce", 2);
        sentiments.put( "rápido", 2);
        sentiments.put( "rápido", 2);
        sentiments.put( "estafa", -3);
        sentiments.put( "estafas", -3);
        sentiments.put( "estafa", -3);
        sentiments.put( "simpática", 2);
        sentiments.put( "lágrimas", -2);
        sentiments.put( "ofertas", 2);
        sentiments.put( "tensa", -2);
        sentiments.put( "tensión", -1);
        sentiments.put( "horrible", -3);
        sentiments.put( "terrible", -3);
        sentiments.put( "fenomenal", 4);
        sentiments.put( "terror", -3);
        sentiments.put( "aterrorizar", -3);
        sentiments.put( "aterrorizada", -3);
        sentiments.put( "aterrorizar", -3);
        sentiments.put( "gracias", 2);
        sentiments.put( "gracias", 2);
        sentiments.put( "pensativo", 2);
        sentiments.put( "desconsiderada", -2);
        sentiments.put( "amenaza", -2);
        sentiments.put( "verdadero", -2);
        sentiments.put( "amenaza", -2);
        sentiments.put( "amenazando", -2);
        sentiments.put( "amenazas", -2);
        sentiments.put( "excitación", 5);
        sentiments.put( "cansado", -2);
        sentiments.put( "totalitaria", -2);
        sentiments.put( "totalitarismo", -2);
        sentiments.put( "desdentado", -2);
        sentiments.put( "top", 2);
        sentiments.put( "picos", 2);
        sentiments.put( "tortura", -4);
        sentiments.put( "torturado", -4);
        sentiments.put( "torturas", -4);
        sentiments.put( "tortura", -4);
        sentiments.put( "tout", -2);
        sentiments.put( "revendedores", -2);
        sentiments.put( "tout", -2);
        sentiments.put( "promocionando", -2);
        sentiments.put( "tragedia", -2);
        sentiments.put( "trágica", -2);
        sentiments.put( "trampa", -1);
        sentiments.put( "traumas", -3);
        sentiments.put( "traumática", -3);
        sentiments.put( "parodia", -2);
        sentiments.put( "traición", -3);
        sentiments.put( "engaño", -2);
        sentiments.put( "Triunfo", 4);
        sentiments.put( "problemas", -2);
        sentiments.put( "molestó", -2);
        sentiments.put( "problemas", -2);
        sentiments.put( "verdadero", 2);
        sentiments.put( "confianza", 1);
        sentiments.put( "feo", -3);
        sentiments.put( "inaceptable", -2);
        sentiments.put( "aprobado", -2);
        sentiments.put( "increíble", -1);
        sentiments.put( "claro", -1);
        sentiments.put( "no está convencido", -1);
        sentiments.put( "sin confirmar", -1);
        sentiments.put( "rebajada", -2);
        sentiments.put( "socava", -2);
        sentiments.put( "socavado", -2);
        sentiments.put( "rebajada", -2);
        sentiments.put( "incómodo", -2);
        sentiments.put( "paro", -2);
        sentiments.put( "poco ético", -2);
        sentiments.put( "infeliz", -2);
        sentiments.put( "impresionado", -2);
        sentiments.put( "unido", 1);
        sentiments.put( "poco profesional", -2);
        sentiments.put( "unresearched", -2);
        sentiments.put( "insatisfecho", -2);
        sentiments.put( "sin mancha", 2);
        sentiments.put( "molesto", -2);
        sentiments.put( "molestar", -2);
        sentiments.put( "molesto", -2);
        sentiments.put( "urgente", -1);
        sentiments.put( "útil", 2);
        sentiments.put( "utilidad", 2);
        sentiments.put( "inútil", -2);
        sentiments.put( "inutilidad", -2);
        sentiments.put( "recuperó", 1);
        sentiments.put( "vulnerables", 2);
        sentiments.put( "sí", 1);
        sentiments.put( "sí", 1);
        sentiments.put( "jaaa", 2);
        sentiments.put( "asqueroso", -2);
        sentiments.put( "delicioso", 3);
        sentiments.put( "vaga", -2);
        sentiments.put( "juicio", -1);
        sentiments.put( "juicios", -1);
        sentiments.put( "la víctima", -3);
        sentiments.put( "víctimas", -3);
        sentiments.put( "la violencia", -3);
        sentiments.put( "violenta", -3);
        sentiments.put( "virtuoso", 2);
        sentiments.put( "visión", 1);
        sentiments.put( "visionario", 3);
        sentiments.put( "visiones", 1);
        sentiments.put( "visión", 1);
        sentiments.put( "vitalidad", 3);
        sentiments.put( "vitamina", 1);
        sentiments.put( "vulnerables", -2);
        sentiments.put( "paro", -2);
        sentiments.put( "paros", -2);
        sentiments.put( "deseos", 1);
        sentiments.put( "guerra", -2);
        sentiments.put( "guerra", -2);
        sentiments.put( "caliente", 1);
        sentiments.put( "caliente", 2);
        sentiments.put( "advertencia", -3);
        sentiments.put( "advertencias", -3);
        sentiments.put( "advertir", -2);
        sentiments.put( "advertencia", -2);
        sentiments.put( "advertencia", -2);
        sentiments.put( "advertir", -2);
        sentiments.put( "residuos", -1);
        sentiments.put( "desperdiciado", -2);
        sentiments.put( "perder el tiempo", -2);
        sentiments.put( "débil", -2);
        sentiments.put( "debilidad", -2);
        sentiments.put( "riqueza", 3);
        sentiments.put( "próspero", 2);
        sentiments.put( "llorar", -2);
        sentiments.put( "llorando", -2);
        sentiments.put( "raro", -2);
        sentiments.put( "bienvenida", 2);
        sentiments.put( "bienvenida", 2);
        sentiments.put( "cal", -3);
        sentiments.put( "puta", -4);
        sentiments.put( "viuda", -1);
        sentiments.put( "preparación", 2);
        sentiments.put( "win", 4);
        sentiments.put( "ganador", 4);
        sentiments.put( "ganador", 4);
        sentiments.put( "WINWIN", 3);
        sentiments.put( "win", 3);
        sentiments.put( "deseos", 1);
        sentiments.put( "deseos", 1);
        sentiments.put( "deseos", 1);
        sentiments.put( "retirada", -3);
        sentiments.put( "ganado", 3);
        sentiments.put( "grande", 4);
        sentiments.put( "woohoo", 3);
        sentiments.put( "Woo", 3);
        sentiments.put( "wooo", 4);
        sentiments.put( "lana", 4);
        sentiments.put( "preocupe", -3);
        sentiments.put( "preocupado", -3);
        sentiments.put( "preocupante", -3);
        sentiments.put( "peor", -3);
        sentiments.put( "deteriora", -3);
        sentiments.put( "empeoró", -3);
        sentiments.put( "deterioro", -3);
        sentiments.put( "deteriora", -3);
        sentiments.put( "peor", -3);
        sentiments.put( "vale la pena", 2);
        sentiments.put( "wow", 4);
        sentiments.put( "WOWOW", 4);
        sentiments.put( "wowww", 4);
        sentiments.put( "error", -2);
        sentiments.put( "fail", -2);
        sentiments.put( "fanático", -2);
        sentiments.put( "fanáticos", -2);
        sentiments.put( "bully", -2);
        sentiments.put( "desorden", -1);
        sentiments.put( "Knol", -1);
        sentiments.put( "tubo", -1);
        sentiments.put( "clase", 3);
        sentiments.put( "fresco", 4);
        sentiments.put( "directo", 3);
        sentiments.put( "feliz", 3);
        sentiments.put( "agradable", 3);
        sentiments.put( "dulce", 3);
        sentiments.put( "mejor", 5);
        sentiments.put( "mejor", 4);
        sentiments.put( "mejor", 3);
        sentiments.put( "bonita", 3);
        sentiments.put( "divertida", 3);
        sentiments.put( "cuidar", 4);
        sentiments.put( "amargo", -1);
        sentiments.put( "duro", 3);
        sentiments.put( "vigorosa", 2);
        sentiments.put( "bello", 4);
        sentiments.put( "oro", 1);
        sentiments.put( "positivo", 2);
        sentiments.put( "divertida", 2);
        sentiments.put( "fuerte", 1);
        sentiments.put( "super", 2);
        sentiments.put( "super cool", 3);
        sentiments.put( "alentador", 2);
        sentiments.put( "alentador", 2);
        sentiments.put( "animó", 2);
        sentiments.put( "fino", 3);
        sentiments.put( "le gusta", 3);
        sentiments.put( "bueno", 2);
        sentiments.put( "agradable", 2);
        sentiments.put( "guapo", 2);
        sentiments.put( "guapo", 2);
        sentiments.put( "útil", 1);
        sentiments.put( "útil", 1);
        sentiments.put( "útil", 1);
        sentiments.put( "valiente", 3);
        sentiments.put( "confort", 2);
        sentiments.put( "confort", 2);
        sentiments.put( "consolado", 2);
        sentiments.put( "agradable", 2);
        sentiments.put( "rayo de sol", 3);
        sentiments.put( "pieza única", 3);        
        
        
        

       

    }

}
